import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import TopBar from "./_components/TopBar/TopBar";
import ServiceBar from "./_components/ServiceBar/ServiceBar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MyProvider from "./_components/MyProvider/MyProvider";
import CartContextProvider from "../context/CartContext";
import WishlistContextProvider from "../context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MyProvider>
          <CartContextProvider>
            <WishlistContextProvider>
              <TopBar />
              <Navbar />
              {children}
              <Toaster />
              <ServiceBar />
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MyProvider>
      </body>
    </html>
  );
}
